# Generated by Django 3.0.4 on 2020-03-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='realm',
            field=models.CharField(help_text='Device realm', max_length=16),
        ),
        migrations.AlterField(
            model_name='device',
            name='user',
            field=models.CharField(help_text='Device user', max_length=16),
        ),
    ]
