# Generated by Django 3.0.4 on 2020-03-29 02:11

import device.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('identifier', device.models.RandomIdentifierField(default=device.models.GenerateIdentifier(16, '0123456789ABCDEF'), help_text='Device identifier', max_length=16, primary_key=True, serialize=False)),
                ('realm', models.CharField(help_text='Device realm', max_length=8)),
                ('user', models.CharField(help_text='Device user', max_length=8)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Creation date')),
                ('last_update', models.DateTimeField(auto_now=True, help_text='Last update')),
            ],
        ),
    ]
